# Generated by Django 4.0.3 on 2022-03-24 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Yangilik uchun rasim')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Sarlavha')),
                ('blog', models.TextField(verbose_name='Maqola')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Published date')),
            ],
        ),
        migrations.CreateModel(
            name='Kamisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Kamisa nomi')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Partia nomini kiriting')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TownsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Tuman Nomi')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KamisaAzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name="To'liq ismi")),
                ('lavozim_type', models.CharField(choices=[('Komissia rayisi', 'Komissia rayisi'), ("Komissia rayisi o'rinbosari", "Komissia rayisi o'rinbosari"), ('Komissia azolari', 'Komissia azolari')], default='Komissia azolari', max_length=50, verbose_name='Lavozim turi')),
                ('lavozim_now', models.CharField(max_length=250, verbose_name='Hozirgi egallab turgan lavozimi')),
                ('number', models.CharField(max_length=25, verbose_name='Saylangan saylov okrugi')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('kamisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kamisa', verbose_name='Qaysi kamisaga azo')),
            ],
        ),
        migrations.CreateModel(
            name='Deputat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name="To'liq ismi")),
                ('phone', models.CharField(max_length=10, verbose_name='Telefon raqami')),
                ('email', models.EmailField(max_length=254, verbose_name='Electron pochta')),
                ('faks', models.CharField(max_length=9, verbose_name='Faks nomeri')),
                ('image', models.ImageField(upload_to='', verbose_name='Rasmi')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('partia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partia', verbose_name='Qaysi partia')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.townsname', verbose_name='Qaysi tuman')),
            ],
        ),
    ]
