# Generated by Django 4.0.3 on 2022-04-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='townsname',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tuman Nomi'),
        ),
    ]
