# Generated by Django 4.0.3 on 2022-05-03 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_komissia_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Senator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=300, verbose_name="Senatorning to'liq ismi")),
                ('senat_img', models.ImageField(height_field=400, upload_to='senator_images/', verbose_name='Senator rasmi')),
                ('phone', models.IntegerField(verbose_name='Telefon raqami')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Pochta manzili')),
                ('faks', models.IntegerField(verbose_name='Faks Nomeri')),
            ],
        ),
        migrations.AddField(
            model_name='komissiaazo',
            name='azo_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='Komisia_Azolar/', verbose_name="A'zoning rasmi"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(upload_to='Blogs/', verbose_name='Yangilik uchun rasim'),
        ),
        migrations.AlterField(
            model_name='deputat',
            name='image',
            field=models.ImageField(upload_to='Deputatlar/', verbose_name='Rasmi'),
        ),
    ]
