# Generated by Django 4.0.3 on 2022-05-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_senator_komissiaazo_azo_img_alter_blogs_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('phone', models.IntegerField(verbose_name='Phone Number')),
                ('subject', models.CharField(max_length=150, verbose_name='Mazmuni')),
                ('comment', models.TextField(verbose_name='Izoh')),
            ],
        ),
    ]
