# Generated by Django 4.0.3 on 2022-05-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_taklif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Fayl nomi')),
                ('file', models.FileField(upload_to='Xujjatlar', verbose_name='Fayl')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqti')),
            ],
        ),
    ]
