# Generated by Django 4.0.3 on 2022-05-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='lang',
            field=models.CharField(choices=[('uz', 'UZ'), ('уз', 'УЗ')], default='uz', max_length=50, verbose_name='Tilni tanlang'),
        ),
    ]
