# Generated by Django 4.0.3 on 2022-05-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_blogs_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senator',
            name='senat_img',
            field=models.ImageField(upload_to='senator_images/', verbose_name='Senator rasmi'),
        ),
    ]
