# Generated by Django 4.0.3 on 2022-05-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_senator_senat_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qisqa_yangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlovha')),
                ('xabar', models.TextField(verbose_name='Yangilik Mazmuni')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
